import { db } from '@/db';
import { murid } from '@/db/schema';

async function main() {
    const sampleMurid = [
        // Class 1 (X-A) - 4 students
        {
            penggunaId: 5,
            nisn: '0051234567',
            nama: 'Andi Pratama',
            jenisKelamin: 'L',
            tanggalLahir: '2008-05-12',
            alamat: 'Jl. Merdeka No. 15, Jakarta',
            kelasId: 1,
            namaOrangTua: 'Bapak Hendra Pratama',
            noTelpOrangTua: '081234560001',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234568',
            nama: 'Dewi Kusuma',
            jenisKelamin: 'P',
            tanggalLahir: '2008-08-20',
            alamat: 'Jl. Sudirman No. 22, Jakarta',
            kelasId: 1,
            namaOrangTua: 'Ibu Sri Kusuma',
            noTelpOrangTua: '081234560002',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234569',
            nama: 'Rizky Ramadhan',
            jenisKelamin: 'L',
            tanggalLahir: '2008-03-15',
            alamat: 'Jl. Gatot Subroto No. 8, Jakarta',
            kelasId: 1,
            namaOrangTua: 'Bapak Agus Ramadhan',
            noTelpOrangTua: '081234560003',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234570',
            nama: 'Sari Wulandari',
            jenisKelamin: 'P',
            tanggalLahir: '2008-11-07',
            alamat: 'Jl. Ahmad Yani No. 45, Jakarta',
            kelasId: 1,
            namaOrangTua: 'Ibu Rina Wulandari',
            noTelpOrangTua: '081234560004',
            createdAt: new Date().toISOString(),
        },
        // Class 2 (X-B) - 4 students
        {
            nisn: '0051234571',
            nama: 'Budi Setiawan',
            jenisKelamin: 'L',
            tanggalLahir: '2008-06-25',
            alamat: 'Jl. Diponegoro No. 33, Jakarta',
            kelasId: 2,
            namaOrangTua: 'Bapak Bambang Setiawan',
            noTelpOrangTua: '081234560005',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234572',
            nama: 'Indah Permata',
            jenisKelamin: 'P',
            tanggalLahir: '2008-09-18',
            alamat: 'Jl. Hayam Wuruk No. 12, Jakarta',
            kelasId: 2,
            namaOrangTua: 'Ibu Dian Permata',
            noTelpOrangTua: '081234560006',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234573',
            nama: 'Fauzi Rahman',
            jenisKelamin: 'L',
            tanggalLahir: '2008-02-28',
            alamat: 'Jl. Cendrawasih No. 27, Jakarta',
            kelasId: 2,
            namaOrangTua: 'Bapak Irfan Rahman',
            noTelpOrangTua: '081234560007',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0051234574',
            nama: 'Nur Azizah',
            jenisKelamin: 'P',
            tanggalLahir: '2008-12-10',
            alamat: 'Jl. Melati No. 19, Jakarta',
            kelasId: 2,
            namaOrangTua: 'Ibu Siti Azizah',
            noTelpOrangTua: '081234560008',
            createdAt: new Date().toISOString(),
        },
        // Class 3 (XI-IPA-1) - 4 students
        {
            nisn: '0041234567',
            nama: 'Dimas Prasetyo',
            jenisKelamin: 'L',
            tanggalLahir: '2007-04-16',
            alamat: 'Jl. Kartini No. 41, Jakarta',
            kelasId: 3,
            namaOrangTua: 'Bapak Eko Prasetyo',
            noTelpOrangTua: '081234560009',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234568',
            nama: 'Lina Marlina',
            jenisKelamin: 'P',
            tanggalLahir: '2007-07-22',
            alamat: 'Jl. Pahlawan No. 56, Jakarta',
            kelasId: 3,
            namaOrangTua: 'Ibu Yuli Marlina',
            noTelpOrangTua: '081234560010',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234569',
            nama: 'Hendra Gunawan',
            jenisKelamin: 'L',
            tanggalLahir: '2007-01-09',
            alamat: 'Jl. Veteran No. 14, Jakarta',
            kelasId: 3,
            namaOrangTua: 'Bapak Joko Gunawan',
            noTelpOrangTua: '081234560011',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234570',
            nama: 'Maya Sari',
            jenisKelamin: 'P',
            tanggalLahir: '2007-10-30',
            alamat: 'Jl. Pemuda No. 28, Jakarta',
            kelasId: 3,
            namaOrangTua: 'Ibu Ani Sari',
            noTelpOrangTua: '081234560012',
            createdAt: new Date().toISOString(),
        },
        // Class 4 (XI-IPA-2) - 4 students
        {
            nisn: '0041234571',
            nama: 'Arif Wijaya',
            jenisKelamin: 'L',
            tanggalLahir: '2007-05-14',
            alamat: 'Jl. Kembang No. 37, Jakarta',
            kelasId: 4,
            namaOrangTua: 'Bapak Wahyu Wijaya',
            noTelpOrangTua: '081234560013',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234572',
            nama: 'Fitri Handayani',
            jenisKelamin: 'P',
            tanggalLahir: '2007-08-27',
            alamat: 'Jl. Mawar No. 52, Jakarta',
            kelasId: 4,
            namaOrangTua: 'Ibu Tuti Handayani',
            noTelpOrangTua: '081234560014',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234573',
            nama: 'Rendi Saputra',
            jenisKelamin: 'L',
            tanggalLahir: '2007-02-19',
            alamat: 'Jl. Anggrek No. 9, Jakarta',
            kelasId: 4,
            namaOrangTua: 'Bapak Dedi Saputra',
            noTelpOrangTua: '081234560015',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0041234574',
            nama: 'Putri Rahayu',
            jenisKelamin: 'P',
            tanggalLahir: '2007-11-05',
            alamat: 'Jl. Kenanga No. 23, Jakarta',
            kelasId: 4,
            namaOrangTua: 'Ibu Eka Rahayu',
            noTelpOrangTua: '081234560016',
            createdAt: new Date().toISOString(),
        },
        // Class 5 (XII-IPA-1) - 4 students
        {
            nisn: '0031234567',
            nama: 'Irfan Hakim',
            jenisKelamin: 'L',
            tanggalLahir: '2006-03-21',
            alamat: 'Jl. Dahlia No. 64, Jakarta',
            kelasId: 5,
            namaOrangTua: 'Bapak Ahmad Hakim',
            noTelpOrangTua: '081234560017',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234568',
            nama: 'Ratna Dewi',
            jenisKelamin: 'P',
            tanggalLahir: '2006-06-13',
            alamat: 'Jl. Flamboyan No. 18, Jakarta',
            kelasId: 5,
            namaOrangTua: 'Ibu Wati Dewi',
            noTelpOrangTua: '081234560018',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234569',
            nama: 'Taufik Hidayat',
            jenisKelamin: 'L',
            tanggalLahir: '2006-09-08',
            alamat: 'Jl. Sakura No. 31, Jakarta',
            kelasId: 5,
            namaOrangTua: 'Bapak Usman Hidayat',
            noTelpOrangTua: '081234560019',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234570',
            nama: 'Sinta Maharani',
            jenisKelamin: 'P',
            tanggalLahir: '2006-12-26',
            alamat: 'Jl. Teratai No. 47, Jakarta',
            kelasId: 5,
            namaOrangTua: 'Ibu Linda Maharani',
            noTelpOrangTua: '081234560020',
            createdAt: new Date().toISOString(),
        },
        // Class 6 (XII-IPA-2) - 4 students
        {
            nisn: '0031234571',
            nama: 'Eko Prasetyo',
            jenisKelamin: 'L',
            tanggalLahir: '2006-04-17',
            alamat: 'Jl. Cempaka No. 55, Jakarta',
            kelasId: 6,
            namaOrangTua: 'Bapak Hadi Prasetyo',
            noTelpOrangTua: '081234560021',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234572',
            nama: 'Diah Ayu',
            jenisKelamin: 'P',
            tanggalLahir: '2006-07-29',
            alamat: 'Jl. Bougenville No. 11, Jakarta',
            kelasId: 6,
            namaOrangTua: 'Ibu Sari Ayu',
            noTelpOrangTua: '081234560022',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234573',
            nama: 'Yoga Aditya',
            jenisKelamin: 'L',
            tanggalLahir: '2006-10-12',
            alamat: 'Jl. Tulip No. 39, Jakarta',
            kelasId: 6,
            namaOrangTua: 'Bapak Andi Aditya',
            noTelpOrangTua: '081234560023',
            createdAt: new Date().toISOString(),
        },
        {
            nisn: '0031234574',
            nama: 'Wulan Sari',
            jenisKelamin: 'P',
            tanggalLahir: '2006-01-24',
            alamat: 'Jl. Seruni No. 26, Jakarta',
            kelasId: 6,
            namaOrangTua: 'Ibu Ratih Sari',
            noTelpOrangTua: '081234560024',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(murid).values(sampleMurid);
    
    console.log(`✅ Murid seeder completed successfully - ${sampleMurid.length} students inserted`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
    process.exit(1);
});